name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
    
      - uses: jsumners/gh-action-hugo-deploy@v1.0.0
        with:
          destination_repo: ipedrazas/ipedrazas.github.io
          destination_token: ${{ secrets.Deploy_Token }}
