name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: true

    - uses: ipedrazas/hugo:v1.0.0
      with:
        destination_repo: ipedrazas/ipedrazas.github.io
        destination_token: ${{ secrets.Deploy_Token }}
